// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/ticker/ticker.proto

/*
Package go_micro_srv_ticker is a generated protocol buffer package.

It is generated from these files:
	proto/ticker/ticker.proto

It has these top-level messages:
	TickerList
	CoinItem
	GetRequest
*/
package go_micro_srv_ticker

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"
import _ "github.com/opsee/protobuf/opseeproto"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for TickerService service

type TickerServiceClient interface {
	GetAll(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*TickerList, error)
}

type tickerServiceClient struct {
	c           client.Client
	serviceName string
}

func NewTickerServiceClient(serviceName string, c client.Client) TickerServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "go.micro.srv.ticker"
	}
	return &tickerServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *tickerServiceClient) GetAll(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*TickerList, error) {
	req := c.c.NewRequest(c.serviceName, "TickerService.GetAll", in)
	out := new(TickerList)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TickerService service

type TickerServiceHandler interface {
	GetAll(context.Context, *GetRequest, *TickerList) error
}

func RegisterTickerServiceHandler(s server.Server, hdlr TickerServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&TickerService{hdlr}, opts...))
}

type TickerService struct {
	TickerServiceHandler
}

func (h *TickerService) GetAll(ctx context.Context, in *GetRequest, out *TickerList) error {
	return h.TickerServiceHandler.GetAll(ctx, in, out)
}
